sudo: required
addons:
  apt:
    sources: &common_sources
      - ubuntu-toolchain-r-test
    packages: &common_packages
      - oracle-java8-installer
      - libstdc++6
      - libstdc++6-4.7-dev
      - gcc-4.9
      - g++-4.9
      - swig
      - ccache

services:
- docker

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons: &llvm40
        apt:
          sources:
            - *common_sources
            - llvm-toolchain-trusty-4.0
          packages:
            - *common_packages
            - clang-4.0
            - libllvm4.0
            - llvm-4.0
            - llvm-4.0-dev
            - llvm-4.0-runtime
      env:
      - TESTED_LANGS="C Cpp IR"
      - CLANG_BIN=clang-4.0

    - os: linux
      jdk: oraclejdk8
      addons: &llvm50
        apt:
          sources:
            - *common_sources
            - llvm-toolchain-trusty-5.0
          packages:
            - *common_packages
            - clang-5.0
            - libllvm5.0
            - llvm-5.0
            - llvm-5.0-dev
            - llvm-5.0-runtime
      env:
      - TESTED_LANGS="C Cpp IR"
      - CLANG_BIN=clang-5.0

    - os: linux
      jdk: oraclejdk8
      env:
      - TESTED_LANGS=Rust
      - RUST_BIN=$HOME/.cargo/bin/rustc

    - os: osx
      osx_image: xcode8
      env: TESTED_LANGS="C Cpp ObjectiveC"

    - os: osx
      osx_image: xcode7.3
      env: TESTED_LANGS="C Cpp ObjectiveC"

language: java

before_install:
 - docker run -d -p 8080:8080 sanitytool/bitreader-service

install:
 - export SANITY_PROFILE=parser-remote
 - ./install.sh

script: bash travis_script.sh

after_success:
  - bash check.sh

after_failure:
  - diff tests/target/failures/expected tests/target/failures/actual
  - cat hs_err*.log 

notifications:
  email: false
  slack: staticanalyzers:8CXJTuMbcNHE7COl24xZuz9G

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.ccache
    - $HOME/Library/Caches/Homebrew
