sudo: required

matrix:
  allow_failures:
    - os: linux
  include:
    - os: linux
    #- os: osx
    #  osx_image: xcode8 # todo fix it if it's fixable, last result: jvm crash in jni code
    - os: osx
      osx_image: xcode7.3
      env:
      - DESCRIPTION=Latest supported OSX image with original llvm libs and released clang
      - REAL_LLVM=1
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode7.1
    - os: osx
      osx_image: xcode7
    #- os: osx
    #  osx_image: xcode6.4
    #- os: osx
    #  osx_image: beta-xcode6.3
    #- os: osx
    #  osx_image: beta-xcode6.2
    #- os: osx
    #  osx_image: beta-xcode6.1

language: java

before_install:
  - ./install.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - diff target/failures/expected target/failures/actual
  - cat hs_err*.log 

notifications:
  email: false
  slack: staticanalyzers:8CXJTuMbcNHE7COl24xZuz9G