sudo: required

os: osx
osx_image: xcode7.3
language: java

notifications:
  email: false

before_install:
  - brew update
  - brew install swig
  - brew install llvm --dsym

after_failure:
  - cat hs_err*.log 
