sudo: false
addons:
  apt:
    sources: &common_sources
      - ubuntu-toolchain-r-test
    packages: &common_packages
      - oracle-java8-installer
      - libstdc++6
      - libstdc++6-4.7-dev
      - gcc-4.9
      - g++-4.9
      - swig
      - ccache

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons: &llvm38
        apt:
          sources:
            - *common_sources
            - llvm-toolchain-precise-3.8
          packages:
            - *common_packages
            - clang-3.8
            - libllvm3.8
            - llvm-3.8
            - llvm-3.8-dev
            - llvm-3.8-runtime
      env:
      - LANG=C
      - CLANG_BIN=clang-3.8
    - os: linux
      jdk: oraclejdk8
      addons: *llvm38
      env:
      - LANG=Cpp
      - CLANG_BIN=clang-3.8
    - os: linux
      jdk: oraclejdk8
      addons: *llvm38
      env:
      - LANG=IR
      - LLVM_AS_BIN=llvm-as-3.8

    - os: linux
      jdk: oraclejdk8
      addons: &llvm39
        apt:
          sources:
            - *common_sources
            - llvm-toolchain-precise-3.9
          packages:
            - *common_packages
            - clang-3.9
            - libllvm3.9
            - llvm-3.9
            - llvm-3.9-dev
            - llvm-3.9-runtime
      env:
      - LANG=C
      - CLANG_BIN=clang-3.9
    - os: linux
      jdk: oraclejdk8
      addons: *llvm39
      env:
      - LANG=Cpp
      - CLANG_BIN=clang-3.9
    - os: linux
      jdk: oraclejdk8
      addons: *llvm39
      env:
      - LANG=IR
      - LLVM_AS_BIN=llvm-as-3.9

    - os: linux
      jdk: oraclejdk8
      addons: &llvm40
        apt:
          sources:
            - *common_sources
            - llvm-toolchain-trusty-4.0
          packages:
            - *common_packages
            - clang-4.0
            - libllvm4.0
            - llvm-4.0
            - llvm-4.0-dev
            - llvm-4.0-runtime
      env:
      - LANG=C
      - CLANG_BIN=clang-4.0
    - os: linux
      jdk: oraclejdk8
      addons: *llvm40
      env:
      - LANG=Cpp
      - CLANG_BIN=clang-4.0
    - os: linux
      jdk: oraclejdk8
      addons: *llvm40
      env:
      - LANG=IR
      - LLVM_AS_BIN=llvm-as-4.0

    - os: linux
      jdk: oraclejdk8
      env:
      - LANG=Rust
      - RUST_BIN=$HOME/.cargo/bin/rustc

    - os: osx
      osx_image: xcode8
      env: LANG=C
    - os: osx
      osx_image: xcode8
      env: LANG=Cpp
    - os: osx
      osx_image: xcode8
      env: LANG=ObjectiveC

    - os: osx
      osx_image: xcode7.3
      env: LANG=C
    - os: osx
      osx_image: xcode7.3
      env: LANG=Cpp
    - os: osx
      osx_image: xcode7.3
      env: LANG=ObjectiveC

# travis uses 7.3 for those below:
#    - os: osx
#      osx_image: xcode7.2
#    - os: osx
#      osx_image: xcode7.1
#    - os: osx
#      osx_image: xcode7

    - os: osx
      osx_image: xcode6.4
      env: LANG=C
    - os: osx
      osx_image: xcode6.4
      env: LANG=Cpp
    - os: osx
      osx_image: xcode6.4
      env: LANG=ObjectiveC

# travis uses 6.4 for those below:
#    - os: osx
#      osx_image: beta-xcode6.3
#      env: LANG=C
#    - os: osx
#      osx_image: beta-xcode6.3
#      env: LANG=Cpp
#    - os: osx
#      osx_image: beta-xcode6.3
#      env: LANG=ObjectiveC
#
#    - os: osx
#      osx_image: beta-xcode6.2
#      env: LANG=C
#    - os: osx
#      osx_image: beta-xcode6.2
#      env: LANG=Cpp
#    - os: osx
#      osx_image: beta-xcode6.2
#      env: LANG=ObjectiveC
#
#    - os: osx
#      osx_image: beta-xcode6.1
#      env: LANG=C
#    - os: osx
#      osx_image: beta-xcode6.1
#      env: LANG=Cpp
#    - os: osx
#      osx_image: beta-xcode6.1
#      env: LANG=ObjectiveC

    - os: osx
      osx_image: xcode7.3
      env:
      - LANG=C
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang
    - os: osx
      osx_image: xcode7.3
      env:
      - LANG=Cpp
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang
    - os: osx
      osx_image: xcode7.3
      env:
      - LANG=ObjectiveC
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang

# brew don't have those below:
#    - os: osx
#      osx_image: xcode7.1
#      env:
#      - EXTRA_BREW=llvm33
#      - CLANG_BIN=clang-3.3
#    - os: osx
#      osx_image: xcode7.1
#      env:
#      - EXTRA_BREW=llvm34
#      - CLANG_BIN=clang-3.4
#    - os: osx
#      osx_image: xcode7.1
#      env:
#      - EXTRA_BREW=llvm35
#      - CLANG_BIN=clang-3.5
#    - os: osx
#      osx_image: xcode7.1
#      env:
#      - EXTRA_BREW=llvm36
#      - CLANG_BIN=clang-3.6

    - os: osx
      env:
      - LANG=C
      - EXTRA_BREW=llvm37
      - CLANG_BIN=clang-3.7
    - os: osx
      env:
      - LANG=Cpp
      - EXTRA_BREW=llvm37
      - CLANG_BIN=clang-3.7
    - os: osx
      env:
      - LANG=ObjectiveC
      - EXTRA_BREW=llvm37
      - CLANG_BIN=clang-3.7

    - os: osx
      env:
      - LANG=C
      - EXTRA_BREW=llvm38
      - CLANG_BIN=clang-3.8
    - os: osx
      env:
      - LANG=Cpp
      - EXTRA_BREW=llvm38
      - CLANG_BIN=clang-3.8
    - os: osx
      env:
      - LANG=ObjectiveC
      - EXTRA_BREW=llvm38
      - CLANG_BIN=clang-3.8

    - os: osx
      env:
      - LANG=C
      - EXTRA_BREW=llvm@3.9
      - CLANG_BIN=/usr/local/opt/llvm\@3.9/bin/clang-3.9
    - os: osx
      env:
      - LANG=Cpp
      - EXTRA_BREW=llvm@3.9
      - CLANG_BIN=/usr/local/opt/llvm\@3.9/bin/clang-3.9
    - os: osx
      env:
      - LANG=ObjectiveC
      - EXTRA_BREW=llvm@3.9
      - CLANG_BIN=/usr/local/opt/llvm\@3.9/bin/clang-3.9

    - os: osx
      env:
      - LANG=C
      - EXTRA_BREW=llvm@4
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang-4.0
    - os: osx
      env:
      - LANG=Cpp
      - EXTRA_BREW=llvm@4
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang-4.0
    - os: osx
      env:
      - LANG=ObjectiveC
      - EXTRA_BREW=llvm@4
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang-4.0

    - os: osx
      env:
      - LANG=Rust
      - EXTRA_BREW=rust
      
  allow_failures:
    - env: SANITY_PROFILE=parser-sulong

language: java

install:
 - export SANITY_PROFILE=parser-native
 - ./install.sh

script: mvn -P $SANITY_PROFILE test -B

after_success:
  - ./check.sh
  - bash <(curl -s https://codecov.io/bash) -F $LANG

after_failure:
  - diff tests/target/failures/expected tests/target/failures/actual
  - cat hs_err*.log 

notifications:
  email: false
  slack: staticanalyzers:8CXJTuMbcNHE7COl24xZuz9G
  

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.ccache
