sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - oracle-java8-installer
      - libstdc++6
      - libstdc++6-4.7-dev
      - gcc-4.9
      - g++-4.9
      - swig
      - clang-3.8
      - libllvm3.8
      - llvm-3.8
      - llvm-3.8-dev
      - llvm-3.8-runtime

matrix:
  allow_failures:
  - osx_image: xcode8 # todo fix it if it's fixable, last result: jvm crash in jni code
  include:
    - os: linux
      jdk: oraclejdk8
      env:
      - LANG=C
      - REAL_LLVM=1
      - CLANG_BIN=clang-3.8
    - os: linux
      jdk: oraclejdk8
      env:
      - LANG=Cpp
      - REAL_LLVM=1
      - CLANG_BIN=clang-3.8
    - os: linux
      jdk: oraclejdk8
      env:
      - LANG=IR
      - REAL_LLVM=1
      - LLVM_AS_BIN=llvm-as-3.8

    - os: osx
      osx_image: xcode8
      env: LANG=C
    - os: osx
      osx_image: xcode8
      env: LANG=Cpp
    - os: osx
      osx_image: xcode8
      env: LANG=ObjectiveC

    - os: osx
      osx_image: xcode7.3
      env: LANG=C
    - os: osx
      osx_image: xcode7.3
      env: LANG=Cpp
    - os: osx
      osx_image: xcode7.3
      env: LANG=ObjectiveC

    - os: osx
      osx_image: xcode7.2
      env: LANG=C
    - os: osx
      osx_image: xcode7.2
      env: LANG=Cpp
    - os: osx
      osx_image: xcode7.2
      env: LANG=ObjectiveC

    - os: osx
      osx_image: xcode7.1
      env: LANG=C
    - os: osx
      osx_image: xcode7.1
      env: LANG=Cpp
    - os: osx
      osx_image: xcode7.1
      env: LANG=ObjectiveC

    - os: osx
      osx_image: xcode7
      env: LANG=C
    - os: osx
      osx_image: xcode7
      env: LANG=Cpp
    - os: osx
      osx_image: xcode7
      env: LANG=ObjectiveC

    - os: osx
      osx_image: xcode6.4
      env: LANG=C
    - os: osx
      osx_image: xcode6.4
      env: LANG=Cpp
    - os: osx
      osx_image: xcode6.4
      env: LANG=ObjectiveC

    - os: osx
      osx_image: beta-xcode6.3
      env: LANG=C
    - os: osx
      osx_image: beta-xcode6.3
      env: LANG=Cpp
    - os: osx
      osx_image: beta-xcode6.3
      env: LANG=ObjectiveC

    - os: osx
      osx_image: beta-xcode6.2
      env: LANG=C
    - os: osx
      osx_image: beta-xcode6.2
      env: LANG=Cpp
    - os: osx
      osx_image: beta-xcode6.2
      env: LANG=ObjectiveC

    - os: osx
      osx_image: beta-xcode6.1
      env: LANG=C
    - os: osx
      osx_image: beta-xcode6.1
      env: LANG=Cpp
    - os: osx
      osx_image: beta-xcode6.1
      env: LANG=ObjectiveC


    - os: osx
      osx_image: xcode7.3
      env:
      - DESCRIPTION=Latest supported OSX image with original llvm libs and released clang
      - LANG=C
      - REAL_LLVM=1
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang
    - os: osx
      osx_image: xcode7.3
      env:
      - DESCRIPTION=Latest supported OSX image with original llvm libs and released clang
      - LANG=Cpp
      - REAL_LLVM=1
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang
    - os: osx
      osx_image: xcode7.3
      env:
      - DESCRIPTION=Latest supported OSX image with original llvm libs and released clang
      - LANG=ObjectiveC
      - REAL_LLVM=1
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang


    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=C
      - EXTRA_BREW=llvm33
      - CLANG_BIN=clang-3.3
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=Cpp
      - EXTRA_BREW=llvm33
      - CLANG_BIN=clang-3.3
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=ObjectiveC
      - EXTRA_BREW=llvm33
      - CLANG_BIN=clang-3.3

    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=C
      - EXTRA_BREW=llvm34
      - CLANG_BIN=clang-3.4
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=Cpp
      - EXTRA_BREW=llvm34
      - CLANG_BIN=clang-3.4
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=ObjectiveC
      - EXTRA_BREW=llvm34
      - CLANG_BIN=clang-3.4

    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=C
      - EXTRA_BREW=llvm35
      - CLANG_BIN=clang-3.5
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=Cpp
      - EXTRA_BREW=llvm35
      - CLANG_BIN=clang-3.5
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=ObjectiveC
      - EXTRA_BREW=llvm35
      - CLANG_BIN=clang-3.5

    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=C
      - EXTRA_BREW=llvm36
      - CLANG_BIN=clang-3.6
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=Cpp
      - EXTRA_BREW=llvm36
      - CLANG_BIN=clang-3.6
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=ObjectiveC
      - EXTRA_BREW=llvm36
      - CLANG_BIN=clang-3.6

    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=C
      - EXTRA_BREW=llvm37
      - CLANG_BIN=clang-3.7
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=Cpp
      - EXTRA_BREW=llvm37
      - CLANG_BIN=clang-3.7
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=ObjectiveC
      - EXTRA_BREW=llvm37
      - CLANG_BIN=clang-3.7

    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=C
      - EXTRA_BREW=llvm38
      - CLANG_BIN=clang-3.8
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=Cpp
      - EXTRA_BREW=llvm38
      - CLANG_BIN=clang-3.8
    - os: osx
      osx_image: xcode7.1
      env:
      - LANG=ObjectiveC
      - EXTRA_BREW=llvm38
      - CLANG_BIN=clang-3.8

language: java

install: ./install.sh

after_success:
  - ./check.sh
  - bash <(curl -s https://codecov.io/bash) -F $LANG

after_failure:
  - diff target/failures/expected target/failures/actual
  - cat hs_err*.log 

notifications:
  email: false
  slack: staticanalyzers:8CXJTuMbcNHE7COl24xZuz9G
