sudo: required

os: osx
osx_image: xcode8
language: java

notifications:
  email: false

before_install:
  - brew update
  - brew install swig
  - brew install llvm --with-toolchain

after_failure:
  - cat hs_err*.log 
