sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - oracle-java8-installer
      - libstdc++6
      - libstdc++6-4.7-dev
      - gcc-4.9
      - g++-4.9
      - cmake
      - swig
      - clang-3.8
      - libllvm3.8
      - llvm-3.8
      - llvm-3.8-dev
      - llvm-3.8-runtime

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      env:
      - CLANG_BIN=clang-3.8
      - LLVM_AS_BIN=llvm-as-3.8
    #- os: osx
    #  osx_image: xcode8 # todo fix it if it's fixable, last result: jvm crash in jni code
    - os: osx
      osx_image: xcode7.3
      env:
      - DESCRIPTION=Latest supported OSX image with original llvm libs and released clang
      - CLANG_BIN=/usr/local/opt/llvm/bin/clang
    - os: osx
      osx_image: xcode7.3

# travis uses 7.3 for those below:
#    - os: osx
#      osx_image: xcode7.2
#    - os: osx
#      osx_image: xcode7.1
#    - os: osx
#      osx_image: xcode7

# brew don't have those below:
#    - os: osx
#      osx_image: xcode7.1
#      env:
#      - EXTRA_BREW=llvm33
#      - CLANG_BIN=clang-3.3
#    - os: osx
#      osx_image: xcode7.1
#      env:
#      - EXTRA_BREW=llvm34
#      - CLANG_BIN=clang-3.4
#    - os: osx
#      osx_image: xcode7.1
#      env:
#      - EXTRA_BREW=llvm35
#      - CLANG_BIN=clang-3.5
#    - os: osx
#      osx_image: xcode7.1
#      env:
#      - EXTRA_BREW=llvm36
#      - CLANG_BIN=clang-3.6

    - os: osx
      env:
      - EXTRA_BREW=llvm37
      - CLANG_BIN=clang-3.7
    - os: osx
      env:
      - EXTRA_BREW=llvm38
      - CLANG_BIN=clang-3.8
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: beta-xcode6.3
    - os: osx
      osx_image: beta-xcode6.2
    - os: osx
      osx_image: beta-xcode6.1

language: java

install:
 - export SANITY_PROFILE=parser-native
 - ./install.sh

script: mvn -P $SANITY_PROFILE test -B

after_success:
  - ./check.sh
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - diff target/failures/expected target/failures/actual
  - cat hs_err*.log 

notifications:
  email: false
  slack: staticanalyzers:8CXJTuMbcNHE7COl24xZuz9G
